### ISSUE TITLE
Chunkwmrc Plugins dir not specified

### ISSUE THREAD

**Issue by KyleNehman** [legallyrobert/dots#1]
I cloned your .chunkwmrc and couldn't get anything to run (no errors, installed via homebrew and tried to run manually). Turns out you had no plugin_dir specified. I dunno if other people will need it or not but I added this 

`chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins`

and it worked. I would've made a PR but I didn't want to fork for a one liner

**Comment by legallyrobert** [comment]
Ah, nice catch. I installed from source - I could never get the homebrew tap to work - and hence my plugins directory is ~/.chunkwm_plugins. It is specified on line 8 of my .chunkwmrc,

`chunkc core::plugin_dir ~/.chunkwm_plugins`
